// pc-version/src/components/Banners.tsx
import { useState, useEffect } from 'react';
import axios from 'axios';

interface BannersProps {
    city?: string;
}

export default function Banners({ city = "多伦多" }: BannersProps) {
    const ALL_BANNERS = [
        {
            cities: ['all'],
            gradient: 'linear-gradient(135deg, #00a980 0%, #006e56 100%)',
            badge: '✨ 双十二感恩季 ✨',
            prefix: '领',
            highlight: '165',
            suffix: '元维修补贴',
            cta: '立即领取'
        },
        {
            cities: ['多伦多', '万锦', '列治文山'],
            image_url: 'https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?q=80&w=2074&auto=format&fit=crop', // Toronto vibe
            badge: '多伦多专属',
            prefix: 'GTA',
            highlight: '开荒保洁',
            suffix: '8折起',
            cta: '预约保洁'
        },
        {
            cities: ['温哥华'],
            image_url: 'https://images.unsplash.com/photo-1568282920275-c08126b8686f?q=80&w=2070&auto=format&fit=crop', // Vancouver vibe
            badge: '温哥华特惠',
            prefix: '雨季',
            highlight: '屋顶检修',
            suffix: '免费上门',
            cta: '立即咨询'
        }
    ];

    const [banners, setBanners] = useState<any[]>(ALL_BANNERS);
    const [currentIndex, setCurrentIndex] = useState(0);

    // Filter banners when city changes
    useEffect(() => {
        const filtered = ALL_BANNERS.filter(b =>
            !b.cities || b.cities.includes('all') || b.cities.some(c => city.includes(c))
        );
        setBanners(filtered.length > 0 ? filtered : ALL_BANNERS.slice(0, 1));
        setCurrentIndex(0);
    }, [city]);

    useEffect(() => {
        // Fetch banners from API
        const fetchBanners = async () => {
            try {
                const res = await axios.get('http://localhost:3001/api/banners/active');
                if (res.data && res.data.length > 0) {
                    setBanners(res.data);
                }
            } catch (e) {
                console.error('Failed to fetch banners', e);
            }
        };
        fetchBanners();
    }, []);

    useEffect(() => {
        if (banners.length <= 1) return;
        const interval = setInterval(() => {
            setCurrentIndex((prev) => (prev + 1) % banners.length);
        }, 5000);
        return () => clearInterval(interval);
    }, [banners.length]);

    const currentBanner = banners[currentIndex];

    const handleBannerClick = (banner: any) => {
        if (banner.link_url) {
            window.open(banner.link_url, '_blank');
        }
    };

    return (
        <div className="relative w-full overflow-hidden rounded-2xl shadow-xl h-[300px] md:h-[400px]">
            {/* Banner Content */}
            <div
                className="w-full h-full transition-all duration-500 ease-in-out cursor-pointer relative"
                onClick={() => handleBannerClick(currentBanner)}
            >
                {currentBanner.image_url ? (
                    <img
                        src={currentBanner.image_url}
                        alt="Banner"
                        className="w-full h-full object-cover"
                    />
                ) : (
                    <div
                        className="w-full h-full flex flex-col items-center justify-center text-white p-8 relative"
                        style={{ background: currentBanner.gradient || 'linear-gradient(135deg, #00a980 0%, #006e56 100%)' }}
                    >
                        {currentBanner.badge && (
                            <div className="absolute top-8 bg-white/20 backdrop-blur-sm px-4 py-1.5 rounded-full text-sm font-semibold tracking-wide border border-white/10">
                                {currentBanner.badge}
                            </div>
                        )}

                        <div className="flex items-baseline gap-2 mb-8">
                            {currentBanner.prefix && <span className="text-3xl md:text-4xl font-bold opacity-90">{currentBanner.prefix}</span>}
                            {currentBanner.highlight && <span className="text-6xl md:text-7xl font-extrabold drop-shadow-md">{currentBanner.highlight}</span>}
                            {currentBanner.suffix && <span className="text-3xl md:text-4xl font-bold opacity-90">{currentBanner.suffix}</span>}
                        </div>

                        {currentBanner.cta && (
                            <button className="bg-white text-primary-800 px-8 py-3 rounded-full font-bold text-lg shadow-xl hover:shadow-2xl hover:scale-105 transition-all">
                                {currentBanner.cta}
                            </button>
                        )}
                    </div>
                )}
            </div>

            {/* Indicators */}
            {banners.length > 1 && (
                <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex gap-2">
                    {banners.map((_, idx) => (
                        <button
                            key={idx}
                            onClick={(e) => { e.stopPropagation(); setCurrentIndex(idx); }}
                            className={`transition-all duration-300 rounded-full shadow-sm ${idx === currentIndex ? 'w-8 h-2 bg-white' : 'w-2 h-2 bg-white/50 hover:bg-white/80'}`}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}

// uniapp-version/src/components/Banners.vue
<template>
  <view class="banner-wrapper">
    <swiper
      class="banner-swiper"
      :indicator-dots="true"
      indicator-color="rgba(255,255,255,0.4)"
      indicator-active-color="#ffffff"
      :autoplay="true"
      :interval="4000"
      :circular="true"
    >
      <swiper-item v-for="(banner, index) in banners" :key="index">
        <!-- 1. Dynamic Image Banner (Backend) -->
        <view v-if="banner.image_url" class="banner-item" style="padding:0; position:relative;" @click="handleBannerClick(banner)">
            <image :src="banner.image_url" mode="aspectFill" style="width:100%; height:100%; border-radius:8px;" />
        </view>
        
        <!-- 2. Legacy Gradient Banner (Fallback) -->
        <view v-else class="banner-item" :style="{ background: banner.gradient }">
          <!-- Badge -->
          <view class="banner-badge" v-if="banner.badge">
            <text class="badge-text">{{ banner.badge }}</text>
          </view>
          
          <!-- Main Content -->
          <view class="banner-content">
            <view class="text-row">
              <text class="prefix-text">{{ banner.prefix }}</text>
              <text class="highlight-text">{{ banner.highlight }}</text>
              <text class="suffix-text">{{ banner.suffix }}</text>
            </view>
          </view>
          
          <!-- CTA Button -->
          <view class="cta-btn">
            <text class="cta-text">{{ banner.cta }}</text>
          </view>
        </view>
      </swiper-item>
    </swiper>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { bannersApi } from '@/services/api';

const props = defineProps({
  currentLocation: {
    type: String,
    default: '多伦多'
  }
});

const ALL_BANNERS = [
  {
    cities: ['all'],
    gradient: 'linear-gradient(135deg, #00a980 0%, #006e56 100%)', // Match PC Primary Green
    badge: '✨ 双十二感恩季 ✨',
    prefix: '领',
    highlight: '165',
    suffix: '元维修补贴',
    cta: '立即领取'
  },
  {
    cities: ['多伦多', '万锦', 'Markham', 'Toronto'],
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    badge: '多伦多专属',
    prefix: 'GTA',
    highlight: '开荒保洁',
    suffix: '8折起',
    cta: '预约保洁'
  },
  {
    cities: ['温哥华', 'Vancouver', 'Richmond'],
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
    badge: '温哥华特惠',
    prefix: '雨季',
    highlight: '屋顶检修',
    suffix: '免费上门',
    cta: '立即咨询'
  }
];

const banners = ref<any[]>([]);

const handleBannerClick = (banner: any) => {
    if (!banner.link_url) return;
    
    let url = banner.link_url.trim();

    // 1. Auto-fix "www." to "https://www."
    if (url.startsWith('www.')) {
        url = 'https://' + url;
    }

    // 2. External Link Handling
    if (url.startsWith('http://') || url.startsWith('https://')) {
        // #ifdef H5
        window.open(url, '_blank');
        // #endif
        
        // #ifndef H5
        // For App/MiniProgram, simple copy or todo webview
        uni.setClipboardData({
            data: url,
            success: () => uni.showToast({ title: '链接已复制', icon: 'none' })
        });
        // #endif
    } else {
        // 3. Internal Page Handling
        // Ensure it starts with /
        if (!url.startsWith('/')) {
            url = '/' + url;
        }
        
        uni.navigateTo({
            url: url,
            fail: (err) => {
                console.log('Navigate failed, trying switchTab', err);
                uni.switchTab({
                    url: url,
                    fail: (e) => {
                        console.error('Navigation failed', e);
                        uni.showToast({ title: '无法跳转', icon: 'none' });
                    }
                });
            }
        });
    }
};

watch(() => props.currentLocation, (newVal) => {
    filterBanners();
}, { immediate: true });

function filterBanners() {
    // Priority: API data if available (mocked for now as we don't have real city field in API yet)
    // Mixing local mock data for demo purpose:
    const mockFiltered = ALL_BANNERS.filter(b => 
        !b.cities || b.cities.includes('all') || b.cities.some(c => props.currentLocation.includes(c))
    );
    banners.value = mockFiltered.length ? mockFiltered : [ALL_BANNERS[0]];
}

onMounted(async () => {
    try {
        const res = await bannersApi.getActive();
        if (res && res.length > 0) {
            // For production, we would filter 'res' based on city if backend supported it.
            // For now, we use real data from backend
            banners.value = res; 
        }
    } catch (e) {
        console.error('Fetch banner error', e); 
    }
});

</script>

<style scoped>
.banner-wrapper {
  padding: 12px 16px;
}

.banner-swiper {
  height: 180px;
  border-radius: 8px;
  overflow: hidden;
}

.banner-item {
  width: 100%;
  height: 100%;
  border-radius: 8px;
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  position: relative;
  overflow: hidden;
}

.banner-badge {
  position: absolute;
  top: 12px;
  left: 50%;
  transform: translateX(-50%);
  background-color: rgba(255, 255, 255, 0.25);
  padding: 4px 12px;
  border-radius: 6px;
}

.badge-text {
  font-size: 11px;
  color: #ffffff;
  font-weight: 600;
}

.banner-content {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding-top: 20px;
}

.text-row {
  display: flex;
  flex-direction: row;
  align-items: baseline;
}

.prefix-text {
  font-size: 22px;
  font-weight: 700;
  color: rgba(255, 255, 255, 0.9);
}

.highlight-text {
  font-size: 48px;
  font-weight: 800;
  color: #ffffff;
  margin: 0 4px;
  text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.2);
}

.suffix-text {
  font-size: 22px;
  font-weight: 700;
  color: rgba(255, 255, 255, 0.9);
}

.cta-btn {
  align-self: center;
  background-color: #ffffff;
  padding: 8px 24px;
  border-radius: 20px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.cta-text {
  font-size: 14px;
  font-weight: 700;
  color: #374151;
}
</style>
