// components/BottomNav.tsx

import React from 'react';
import { Home, Grid, Headset, User } from 'lucide-react';

interface BottomNavProps {
  activeTab?: 'home' | 'standard' | 'custom' | 'profile';
  onTabChange?: (tab: 'home' | 'standard' | 'custom' | 'profile') => void;
}

export const BottomNav: React.FC<BottomNavProps> = ({ activeTab = 'home', onTabChange }) => {
  const navItems = [
    { id: 'home', icon: Home, label: '首页' },
    { id: 'standard', icon: Grid, label: '标准服务' },
    { id: 'custom', icon: Headset, label: '定制服务' },
    { id: 'profile', icon: User, label: '我的' },
  ];

  return (
    <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 pb-[env(safe-area-inset-bottom)] pt-2 px-6 flex justify-between z-40 max-w-7xl mx-auto md:hidden">
      {navItems.map((item) => {
        const isActive = activeTab === item.id;
        return (
          <div 
            key={item.id} 
            className="flex flex-col items-center gap-1 p-1 w-16 cursor-pointer hover:bg-gray-50 rounded-lg"
            onClick={() => onTabChange?.(item.id as any)}
          >
            <item.icon 
              size={26} 
              className={`${isActive ? 'text-emerald-600 fill-emerald-600' : 'text-gray-400'}`} 
              strokeWidth={isActive ? 2.5 : 2}
            />
            <span className={`text-xs font-bold ${isActive ? 'text-emerald-600' : 'text-gray-500'}`}>
              {item.label}
            </span>
          </div>
        );
      })}
    </div>
  );
};

// uniapp-version/src/components/BottomNav.vue
<template>
  <view class="bottom-nav">
    <view 
      class="nav-item"
      :class="{ 'nav-item-active': activeTab === 'home' }"
      @click="emit('tabChange', 'home')"
    >
      <view class="icon-container">
        <!-- Home Icon -->
        <AppIcon 
          name="home" 
          :size="28" 
          color="#000000"
          :stroke-width="2.2"
        />
      </view>
      <text 
        class="nav-label"
        :class="activeTab === 'home' ? 'label-active' : 'label-inactive'"
      >
        首页
      </text>
    </view>
    
    <view 
      class="nav-item"
      :class="{ 'nav-item-active': activeTab === 'standard' }"
      @click="emit('tabChange', 'standard')"
    >
      <view class="icon-container">
        <!-- Checklist Icon -->
        <AppIcon 
          name="clipboard" 
          :size="28" 
          color="#000000"
          :stroke-width="2.2"
        />
      </view>
      <text 
        class="nav-label"
        :class="activeTab === 'standard' ? 'label-active' : 'label-inactive'"
      >
        标准服务
      </text>
    </view>
    
    <view 
      class="nav-item"
      :class="{ 'nav-item-active': activeTab === 'custom' }"
      @click="emit('tabChange', 'custom')"
    >
      <view class="icon-container">
        <!-- Headphones Icon -->
        <AppIcon 
          name="headphones" 
          :size="28" 
          color="#000000"
          :stroke-width="2.2"
        />
      </view>
      <text 
        class="nav-label"
        :class="activeTab === 'custom' ? 'label-active' : 'label-inactive'"
      >
        定制服务
      </text>
    </view>
    
    <view 
      class="nav-item"
      :class="{ 'nav-item-active': activeTab === 'profile' }"
      @click="emit('tabChange', 'profile')"
    >
      <view class="icon-container">
        <!-- User Icon -->
        <AppIcon 
          name="user" 
          :size="28" 
          color="#000000"
          :stroke-width="2.2"
        />
      </view>
      <text 
        class="nav-label"
        :class="activeTab === 'profile' ? 'label-active' : 'label-inactive'"
      >
        我的
      </text>
    </view>
  </view>
</template>

<script setup lang="ts">
import AppIcon from './Icons.vue';

defineProps<{
  activeTab: string
}>();

const emit = defineEmits(['tabChange']);
</script>

<style scoped>
.bottom-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 60px; /* Increased slightly */
  padding-bottom: env(safe-area-inset-bottom);
  background-color: #ffffff;
  border-top: 1px solid #f3f4f6;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-around;
  z-index: 100;
  box-shadow: 0 -1px 3px rgba(0,0,0,0.02);
}

.nav-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 4px;
  padding: 8px 0;
}

.icon-container {
  display: flex;
  align-items: center;
  justify-content: center;
  /* Slightly bold the icons by default stroke-width from Icons.vue */
}

/* We removed text icons, so these classes are redundant for icons but active state is handled via props */

.nav-label {
  font-size: 11px; /* Keep font size small for compactness */
  font-weight: 500;
  margin-top: 2px;
}

.label-active {
  color: #059669;
  font-weight: 600; /* Bolder text for active */
}

.label-inactive {
  color: #9ca3af;
}
</style>
