// components/PopularArticles.tsx

import React, { useState, useEffect } from 'react';
import { FileText, ChevronRight } from 'lucide-react';
import { cmsApi, Article } from '../services/api';
import { ArticleDetailModal } from './ArticleDetailModal';

// Fallback data in case API fails
const FALLBACK_ARTICLES: Article[] = [
    {
        id: '1',
        title: '如何选择靠谱的维修师傅？',
        summary: '拒绝踩坑！这3点关键资质一定要看...',
        category: '避坑指南',
        views: 23000
    },
    {
        id: '2',
        title: '家电清洗频率大揭秘',
        summary: '洗衣机不洗比马桶还脏？专家建议...',
        category: '健康生活',
        views: 15000
    },
    {
        id: '3',
        title: '服务验收标准清单',
        summary: '水管修完怎么验？电路安全怎么查？',
        category: '验收干货',
        views: 9800
    },
    {
        id: '4',
        title: '二手房交易流程全解析',
        summary: '从看房到过户，手把手教你搞定...',
        category: '房产百科',
        views: 31000
    }
];

interface PopularArticlesProps {
    onArticleClick?: (articleId: string) => void;
}

export const PopularArticles: React.FC<PopularArticlesProps> = ({ onArticleClick }) => {
    const [articles, setArticles] = useState<Article[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const fetchArticles = async () => {
            try {
                const data = await cmsApi.getArticles({ type: 'article', sort: 'views', limit: 4 });
                if (data && data.articles) {
                    setArticles(data.articles);
                } else {
                    setArticles(FALLBACK_ARTICLES);
                }
            } catch (error) {
                console.error('Failed to fetch articles:', error);
                setArticles(FALLBACK_ARTICLES);
            } finally {
                setIsLoading(false);
            }
        };

        fetchArticles();
    }, []);

    const getLabel = (key?: string) => {
        if (!key) return '文章';
        const map: Record<string, string> = {
            'guide': '避坑指南',
            'health': '健康生活',
            'real_estate': '房产百科',
            'news': '行业资讯'
        };
        return map[key] || key;
    };

    return (
        <div className="px-4 pb-6 mt-4 md:px-8">
            <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                    <div className="w-1 h-5 bg-orange-400 rounded-full"></div>
                    <h2 className="text-xl font-bold text-gray-900">热门文章</h2>
                </div>
                <span className="text-base font-bold text-grey-400 flex items-center gap-0.5 cursor-pointer hover:text-orange-500">
                    更多 <ChevronRight size={16} />
                </span>
            </div>

            {/* Responsive Grid: 1 col on mobile, 2 on md, 4 on lg */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
                {articles.map((article) => (
                    <div
                        key={article.id}
                        onClick={() => onArticleClick?.(article.id)}
                        className="bg-white rounded-xl p-3 border border-gray-100 shadow-[0_2px_8px_rgba(0,0,0,0.02)] active:scale-[0.98] transition-transform cursor-pointer flex flex-col justify-between h-36 hover:shadow-md hover:border-orange-100"
                    >
                        <div>
                            <div className="flex justify-between items-start mb-2">
                                <span className="text-sm font-bold text-orange-500 bg-orange-50 px-2 py-0.5 rounded border border-orange-100">
                                    {getLabel(article.category)}
                                </span>
                            </div>
                            <h3 className="font-bold text-gray-900 text-xl line-clamp-2 leading-snug">
                                {article.title}
                            </h3>
                            <p className="text-base font-bold text-gray-600 mt-1 line-clamp-1">
                                {article.summary || article.content || '暂无简介'}
                            </p>
                        </div>
                        <div className="flex items-center gap-1 mt-2 text-gray-600">
                            <FileText size={12} />
                            <span className="text-sm">{(article.views || 0).toLocaleString()} 阅读</span>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

// uniapp-version/src/components/PopularArticles.vue
<template>
  <view class="px-4 pb-6 mt-4 md-px-8">
      <view class="flex items-center justify-between mb-3">
          <view class="flex items-center gap-2">
              <view class="w-1 h-5 bg-orange-400 rounded-full"></view>
              <text class="text-xl font-bold text-gray-900">热门文章</text>
          </view>
          <view class="text-base font-bold text-grey-400 flex items-center gap-half cursor-pointer hover-text-orange-500">
              <text>更多</text>
              <text class="chevron-icon">›</text>
          </view>
      </view>

      <!-- Responsive Grid: 1 col on mobile, 2 on md, 4 on lg -->
      <!-- Using Flex wrap for grid simulation on mobile -->
      <view class="grid-cols-1 md-grid-cols-2 lg-grid-cols-4 grid gap-3">
          <view 
              v-for="article in formattedArticles" 
              :key="article.id" 
              class="bg-white rounded-xl p-3 border border-gray-100 shadow-custom active-scale-98 transition-transform cursor-pointer flex flex-col justify-between h-36 hover-shadow-md"
              @click="$emit('article-click', article)"
          >
              <view>
                  <view class="flex justify-between items-start mb-2">
                       <text class="text-sm font-bold text-orange-500 bg-orange-50 px-2 py-half rounded border border-orange-100">
                          {{ article.tag || getLabel(article.category) }}
                       </text>
                  </view>
                  <text class="font-bold text-gray-900 text-xl line-clamp-2 leading-snug block">
                      {{ article.title }}
                  </text>
                  <text class="text-base font-bold text-gray-600 mt-1 line-clamp-1 block">
                      {{ article.summary || article.desc || '暂无简介' }}
                  </text>
              </view>
              <view class="flex items-center gap-1 mt-2 text-gray-600">
                  <text class="file-icon">📄</text>
                  <text class="text-sm">{{ article.views || 0 }} 阅读</text>
              </view>
          </view>
      </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { cmsApi } from '@/services/api';

const emit = defineEmits(['article-click']);

const articles = ref<any[]>([]);

// Fallback data if API fails or initially
const fallbackArticles = [
  {
      id: 1,
      title: '如何选择靠谱的维修师傅？',
      desc: '拒绝踩坑！这3点关键资质一定要看...',
      views: '2.3w',
      category: 'guide'
  },
  {
      id: 2,
      title: '家电清洗频率大揭秘',
      desc: '洗衣机不洗比马桶还脏？专家建议...',
      views: '1.5w',
      category: 'health'
  }
];

// Fetch from API
const fetchPopularArticles = async () => {
    try {
        const res = await cmsApi.getArticles({ type: 'article', sort: 'views', limit: 4 });
        if (res.articles && res.articles.length > 0) {
            articles.value = res.articles;
        }
    } catch (e) {
        console.error('Failed to fetch articles');
    }
};

const formattedArticles = computed(() => {
    return articles.value.length > 0 ? articles.value : fallbackArticles;
});

const getLabel = (key: string) => {
    const map: any = {
        'guide': '避坑指南',
        'health': '健康生活',
        'real_estate': '房产百科',
        'news': '行业资讯'
    };
    return map[key] || '文章';
}

onMounted(() => {
    fetchPopularArticles();
});
</script>

<style scoped>
.flex { display: flex; }
.items-center { align-items: center; }
.justify-between { justify-content: space-between; }
.flex-col { flex-direction: column; }

.grid { display: grid; }
.grid-cols-1 { grid-template-columns: repeat(1, 1fr); }
.gap-3 { gap: 12px; }

.bg-white { background-color: #ffffff; }
.bg-orange-400 { background-color: #fb923c; }
.bg-orange-50 { background-color: #fff7ed; }
.text-gray-900 { color: #111827; }
.text-gray-600 { color: #4b5563; }
.text-orange-500 { color: #f97316; }
.text-white { color: #ffffff; }

.border { border-width: 1px; }
.border-gray-100 { border-color: #f3f4f6; }
.border-orange-100 { border-color: #ffedd5; }

.shadow-custom { box-shadow: 0 2px 8px rgba(0,0,0,0.02); }

.px-4 { padding-left: 16px; padding-right: 16px; }
.pb-6 { padding-bottom: 24px; }
.mt-4 { margin-top: 16px; }
.mb-2 { margin-bottom: 8px; }
.mb-3 { margin-bottom: 12px; }
.mt-1 { margin-top: 4px; }
.mt-2 { margin-top: 8px; }
.p-3 { padding: 12px; }
.px-2 { padding-left: 8px; padding-right: 8px; }
.py-half { padding-top: 2px; padding-bottom: 2px; }
.gap-2 { gap: 8px; }
.gap-half { gap: 2px; }
.gap-1 { gap: 4px; }

.w-1 { width: 4px; }
.h-5 { height: 20px; }
.h-36 { height: 144px; }

.rounded-full { border-radius: 9999px; }
.rounded-xl { border-radius: 12px; }
.rounded { border-radius: 4px; }

.text-xl { font-size: 20px; }
.text-lg { font-size: 18px; }
.text-base { font-size: 16px; }
.text-sm { font-size: 14px; }
.font-bold { font-weight: 700; }

.line-clamp-2 {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}
.line-clamp-1 {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 1;
  overflow: hidden;
}
.active-scale-98:active { transform: scale(0.98); }
</style>
