// components/ServiceGrid.tsx


import React, { useState, useEffect } from 'react';
import { AppIcon } from './Icons';
import { categoriesApi, Category } from '../services/api';

interface ServiceGridProps {
  onCategorySelect?: (categoryName: string) => void;
  selectedCategory?: string;
}

// Fallback colors for dynamic categories
const COLORS = [
  'text-cyan-500', 'text-amber-500', 'text-orange-500', 'text-slate-600',
  'text-blue-500', 'text-emerald-500', 'text-indigo-500', 'text-purple-500',
  'text-pink-500', 'text-emerald-600', 'text-teal-600', 'text-blue-600',
  'text-sky-500', 'text-red-500', 'text-blue-500', 'text-teal-400',
  'text-sky-300', 'text-zinc-600'
];

interface UICategory extends Category {
  color: string;
  iconName: string;
}

export const ServiceGrid: React.FC<ServiceGridProps> = ({ onCategorySelect, selectedCategory }) => {
  const [categories, setCategories] = useState<UICategory[]>([]);
  const [currentPage, setCurrentPage] = useState(0);
  const [touchStart, setTouchStart] = useState<number | null>(null);
  const [touchEnd, setTouchEnd] = useState<number | null>(null);

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const data = await categoriesApi.getAll();
        console.log('ServiceGrid fetched categories:', data);
        // Transform
        const uiCategories = (data.categories || []).map((cat, index) => ({
          ...cat,
          iconName: cat.icon || 'grid', // Default fallback
          color: COLORS[index % COLORS.length]
        }));
        setCategories(uiCategories);
      } catch (error) {
        console.error('Failed to fetch categories:', error);
      }
    };
    fetchCategories();
  }, []);

  // 8 items per page for Mobile
  const ITEMS_PER_PAGE = 8;
  const PAGES = [];
  const displayItems = categories.length > 0 ? categories : [];

  for (let i = 0; i < displayItems.length; i += ITEMS_PER_PAGE) {
    PAGES.push(displayItems.slice(i, i + ITEMS_PER_PAGE));
  }


  const minSwipeDistance = 50;

  const onTouchStart = (e: React.TouchEvent) => {
    setTouchEnd(null);
    setTouchStart(e.targetTouches[0].clientX);
  };

  const onTouchMove = (e: React.TouchEvent) => {
    setTouchEnd(e.targetTouches[0].clientX);
  };

  const onTouchEnd = () => {
    if (!touchStart || !touchEnd) return;

    const distance = touchStart - touchEnd;
    const isLeftSwipe = distance > minSwipeDistance;
    const isRightSwipe = distance < -minSwipeDistance;

    if (isLeftSwipe && currentPage < PAGES.length - 1) {
      setCurrentPage(prev => prev + 1);
    }

    if (isRightSwipe && currentPage > 0) {
      setCurrentPage(prev => prev - 1);
    }
  };

  const renderItem = (item: UICategory) => {
    const isSelected = selectedCategory === item.name;
    return (
      <div
        key={item.id}
        className="flex flex-col items-center gap-1 cursor-pointer py-1 hover:opacity-80 transition-opacity"
        onClick={() => onCategorySelect?.(item.name)}
      >
        {/* Icon Container - Neutral Background to let colors pop */}
        <div
          className={`w-[4.5rem] h-[4.5rem] md:w-24 md:h-24 rounded-[1.4rem] md:rounded-[2rem] bg-gray-50 flex items-center justify-center shadow-sm transition-all duration-200 active:scale-95 ${isSelected ? 'ring-2 ring-emerald-600 ring-offset-2' : ''
            }`}
        >
          <AppIcon name={item.iconName} size={42} className={`md:scale-125 transition-transform ${item.color}`} />
        </div>
        {/* Text Size: text-xl on mobile, text-2xl on desktop */}
        <span className={`text-xl md:text-2xl font-bold text-center leading-tight tracking-tight px-0.5 whitespace-nowrap ${isSelected ? 'text-emerald-700' : 'text-gray-800'}`}>
          {item.name}
        </span>
      </div>
    );
  };

  return (
    <div className="bg-white rounded-2xl mx-4 mt-2 px-1 pt-4 pb-3 shadow-[0_2px_8px_rgba(0,0,0,0.04)] border border-gray-100 min-h-[280px] md:mx-8">

      {/* HEADER TITLE SECTION */}
      <div className="px-4 mb-4">
        <div className="bg-emerald-600 text-white py-2.5 px-4 rounded-xl text-center shadow-sm cursor-pointer hover:bg-emerald-700 transition-colors"
          onClick={() => onCategorySelect?.('标准服务')}
        >
          <h3 className="text-xl font-extrabold tracking-wide">
            标准服务，省时，省心
          </h3>
        </div>
      </div>

      {/* MOBILE VIEW: Swipeable Pages */}
      <div
        className="overflow-hidden md:hidden"
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}
      >
        <div
          className="flex transition-transform duration-300 ease-in-out"
          style={{ transform: `translateX(-${currentPage * 100}%)` }}
        >
          {PAGES.map((pageItems, pageIndex) => (
            <div key={pageIndex} className="min-w-full grid grid-cols-4 gap-y-4 gap-x-1">
              {pageItems.map(renderItem)}
            </div>
          ))}
        </div>
      </div>

      {/* MOBILE PAGINATION DOTS */}
      <div className="flex justify-center mt-4 gap-1.5 md:hidden">
        {PAGES.map((_, index) => (
          <button
            key={index}
            onClick={() => setCurrentPage(index)}
            className={`transition-all duration-300 rounded-full h-1.5 ${currentPage === index ? 'w-5 bg-emerald-600' : 'w-1.5 bg-gray-200'
              }`}
          />
        ))}
      </div>

      <div className="hidden md:grid md:grid-cols-6 gap-y-10 gap-x-6 p-8">
        {displayItems.map(renderItem)}
      </div>

    </div>
  );
};

// uniapp-version/src/components/ServiceGrid.vue
<template>
  <view class="service-grid-wrapper">
    <!-- Green Title Bar -->
    <view class="title-bar">
      <text class="title-text">标准服务，省时，省心</text>
    </view>
    
    <!-- White Card Container -->
    <view class="service-card">
      <swiper 
        class="swiper-container"
        :indicator-dots="false"
        @change="onSwiperChange"
      >
        <swiper-item v-for="(pageItems, pageIndex) in pages" :key="pageIndex">
          <view class="grid-container">
            <view 
              v-for="(service, idx) in pageItems" 
              :key="idx" 
              class="grid-item"
              @click="emit('categorySelect', service.name)"
            >
              <view class="icon-wrapper" :style="{ backgroundColor: service.bgColor }">
                 <image 
                   v-if="service.iconName?.startsWith('http')" 
                   :src="service.iconName" 
                   class="w-8 h-8 rounded-full"
                   mode="aspectFill"
                 />
                <AppIcon v-else :name="service.iconName" :size="32" :style="{ color: service.iconColor }" />
              </view>
              <text class="service-name">{{ service.name }}</text>
            </view>
          </view>
        </swiper-item>
      </swiper>
      
      <!-- Pagination Dots -->
      <view class="dots-container">
        <view
          v-for="(_, index) in pages"
          :key="index"
          class="dot"
          :class="{ 'dot-active': currentPage === index }"
        />
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import AppIcon from './Icons.vue';
import { categoriesApi } from '@/services/api';

const emit = defineEmits(['categorySelect']);

defineProps<{
  selectedCategory?: string
}>();

const currentPage = ref(0);
const services = ref<any[]>([]);

const onSwiperChange = (e: any) => {
  currentPage.value = e.detail.current;
};

// Pastel colors for icons
const COLORS = [
  { icon: '#0891b2', bg: 'rgba(8, 145, 178, 0.1)' },
  { icon: '#d97706', bg: 'rgba(217, 119, 6, 0.1)' },
  { icon: '#059669', bg: 'rgba(5, 150, 105, 0.1)' },
  { icon: '#ea580c', bg: 'rgba(234, 88, 12, 0.1)' },
  { icon: '#475569', bg: 'rgba(71, 85, 105, 0.1)' },
  { icon: '#16a34a', bg: 'rgba(22, 163, 74, 0.1)' },
  { icon: '#2563eb', bg: 'rgba(37, 99, 235, 0.1)' },
  { icon: '#7c3aed', bg: 'rgba(124, 58, 237, 0.1)' }
];

const ITEMS_PER_PAGE = 8;
const pages = computed(() => {
    const p: any[] = [];
    for (let i = 0; i < services.value.length; i += ITEMS_PER_PAGE) {
        p.push(services.value.slice(i, i + ITEMS_PER_PAGE));
    }
    return p;
});

onMounted(async () => {
    try {
        const res = await categoriesApi.getAll();
        services.value = (res.categories || []).map((cat: any, index: number) => {
            const color = COLORS[index % COLORS.length];
            return {
                name: cat.name,
                iconName: cat.icon || 'grid', // fallback
                iconColor: color.icon,
                bgColor: color.bg
            };
        });
    } catch (e) {
        console.error('Fetch categories failed', e);
        // Fallback to minimal default if fail? Or just empty.
    }
});
</script>

<style scoped>
.service-grid-wrapper {
  padding: 12px 16px;
}

.title-bar {
  background: linear-gradient(90deg, #047857 0%, #059669 100%);
  border-radius: 8px;
  padding: 12px 24px;
  margin-bottom: 16px;
}

.title-text {
  color: #ffffff;
  font-size: 17px;
  font-weight: 700;
  text-align: center;
  display: block;
}

.service-card {
  background-color: #ffffff;
  border-radius: 12px;
  padding: 16px 8px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.04);
}

.swiper-container {
  height: 220px;
}

.grid-container {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px 4px;
  padding: 0 8px;
}

.grid-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
}

.icon-wrapper {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden; /* Added for image clipping */
}

.service-name {
  font-size: 15px;
  font-weight: 700;
  color: #374151;
  text-align: center;
}

.dots-container {
  display: flex;
  flex-direction: row;
  justify-content: center;
  gap: 6px;
  margin-top: 12px;
}

.dot {
  width: 6px;
  height: 6px;
  border-radius: 3px;
  background-color: #e5e7eb;
  transition: all 0.3s;
}

.dot-active {
  width: 20px;
  background-color: #047857;
}

/* Unified deep green color for all icons */
.text-green-600 { color: #047857; }
</style>
