// pc-version/src/pages/ProfileInfo.tsx
import React, { useState, useEffect } from 'react';
import MobileHeader from '../components/MobileHeader';
import { getUserInfo, authApi, setAuth, getToken } from '../services/api';
import ChangeContactModal from '../components/ChangeContactModal';

export default function ProfileInfo() {
    const [user, setUser] = useState<any>(null);
    const [formData, setFormData] = useState({ surname: '', name: '' });
    const [saving, setSaving] = useState(false);
    const [contactModal, setContactModal] = useState<{ open: boolean; type: 'phone' | 'email' }>({ open: false, type: 'phone' });
    const [msg, setMsg] = useState<{ content: string, type: 'success' | 'error' } | null>(null);

    useEffect(() => {
        const u = getUserInfo();
        setUser(u);
        if (u) {
            setFormData({
                surname: u.name?.charAt(0) || '',
                name: u.name?.slice(1) || ''
            });
        }
    }, [contactModal.open]);

    const handleSave = async () => {
        setMsg(null);
        if (!formData.surname || !formData.name) return setMsg({ content: '请输入完整姓名', type: 'error' });
        setSaving(true);
        try {
            const fullName = formData.surname + formData.name;
            const res = await authApi.updateProfile({ name: fullName });
            setUser(res.user);
            const token = getToken();
            if (token) setAuth(token, res.user);
            setMsg({ content: '保存成功', type: 'success' });
            setTimeout(() => setMsg(null), 2000);
        } catch (e: any) {
            setMsg({ content: e.message || '保存失败', type: 'error' });
        } finally {
            setSaving(false);
        }
    };

    if (!user) return null;

    return (
        <div className="min-h-screen bg-gray-50 pt-14">
            <MobileHeader title="个人信息" />

            <div className="bg-white mt-2 px-4 py-6 space-y-6">
                {/* Avatar */}
                <div className="flex justify-center mb-6">
                    <div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary-100 to-primary-200 flex items-center justify-center text-3xl font-bold text-primary-600 shadow-inner">
                        {user.name?.[0]?.toUpperCase() || 'U'}
                    </div>
                </div>

                <div className="space-y-4">
                    <div>
                        <label className="block text-sm text-gray-500 mb-1">姓</label>
                        <input
                            type="text"
                            value={formData.surname}
                            onChange={e => setFormData({ ...formData, surname: e.target.value })}
                            className="w-full border-b border-gray-200 py-3 text-gray-800 focus:outline-none focus:border-cyan-500 bg-transparent text-base"
                            placeholder="请输入姓"
                        />
                    </div>
                    <div>
                        <label className="block text-sm text-gray-500 mb-1">名</label>
                        <input
                            type="text"
                            value={formData.name}
                            onChange={e => setFormData({ ...formData, name: e.target.value })}
                            className="w-full border-b border-gray-200 py-3 text-gray-800 focus:outline-none focus:border-cyan-500 bg-transparent text-base"
                            placeholder="请输入名"
                        />
                    </div>

                    <div className="pt-2">
                        <label className="block text-sm text-gray-500 mb-1">手机号码</label>
                        <div className="flex justify-between items-center py-3 border-b border-gray-200">
                            <span className="text-gray-800 text-base">{user.phone || '未绑定'}</span>
                            <button onClick={() => setContactModal({ open: true, type: 'phone' })} className="text-sm text-cyan-500 font-medium">修改</button>
                        </div>
                    </div>

                    <div className="pt-2">
                        <label className="block text-sm text-gray-500 mb-1">邮箱</label>
                        <div className="flex justify-between items-center py-3 border-b border-gray-200">
                            <span className="text-gray-800 text-base">{user.email || '未绑定'}</span>
                            <button onClick={() => setContactModal({ open: true, type: 'email' })} className="text-sm text-cyan-500 font-medium">修改</button>
                        </div>
                    </div>
                </div>
            </div>

            {msg && (
                <div className={`text-center text-sm py-2 ${msg.type === 'error' ? 'text-red-500' : 'text-green-500'}`}>
                    {msg.content}
                </div>
            )}

            <div className="p-6 mt-4">
                <button
                    onClick={handleSave}
                    disabled={saving}
                    className="w-full bg-cyan-500 text-white rounded-xl py-3.5 font-medium shadow-lg shadow-cyan-500/30 active:scale-[0.98] transition-all disabled:opacity-70"
                >
                    {saving ? '保存中...' : '保存更改'}
                </button>
            </div>

            <ChangeContactModal
                isOpen={contactModal.open}
                type={contactModal.type}
                onClose={() => setContactModal({ ...contactModal, open: false })}
                onSuccess={(u) => setUser(u)}
            />
        </div>
    );
}

// uniapp-version/src/pages/user/profile-info.vue
<template>
  <view class="min-h-screen bg-gray-50 pb-10">
    <!-- Header -->
    <view class="bg-white px-4 py-3 flex flex-row items-center justify-between sticky top-0 z-10 border-b border-gray-100" :style="{ paddingTop: safeAreaTop + 'px' }">
       <view @click="goBack" class="p-1"><AppIcon name="chevron-left" :size="24" color="#374151" /></view>
       <text class="text-lg font-bold text-gray-800">个人信息</text>
       <view class="w-10 flex items-end" @click="handleSave">
           <text class="text-emerald-600 font-bold text-sm">保存</text>
       </view>
    </view>

    <view class="p-4 flex flex-col items-center mt-4">
        <view class="w-20 h-20 rounded-full bg-emerald-100 flex items-center justify-center mb-4">
             <text class="text-2xl font-bold text-emerald-600" style="line-height: 80px; text-align: center;">{{ formData.name ? formData.name.charAt(0).toUpperCase() : 'U' }}</text>
        </view>
    </view>

    <view class="bg-white mt-4">
         <view class="px-4 py-3 border-b border-gray-100">
             <text class="text-xs text-gray-500 mb-1 block">姓名</text>
             <input class="w-full text-base text-gray-800 h-8" v-model="formData.name" placeholder="请输入姓名" />
         </view>
         <view class="px-4 py-3 border-b border-gray-100 flex flex-row items-center justify-between">
             <view class="flex-1">
                 <text class="text-xs text-gray-500 mb-1 block">手机号码</text>
                 <text class="text-base text-gray-800">{{ userInfo.phone || '未绑定' }}</text>
             </view>
             <text class="text-emerald-600 text-sm font-medium" @click="toChangeContact('phone')">修改</text>
         </view>
         <view class="px-4 py-3 border-b border-gray-100 flex flex-row items-center justify-between">
             <view class="flex-1">
                 <text class="text-xs text-gray-500 mb-1 block">邮箱</text>
                 <text class="text-base text-gray-800">{{ userInfo.email || '未绑定' }}</text>
             </view>
             <text class="text-emerald-600 text-sm font-medium" @click="toChangeContact('email')">修改</text>
         </view>
    </view>

  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, reactive } from 'vue';
import AppIcon from '@/components/Icons.vue';
import { getUserInfo, authApi, setUserInfo, getToken } from '@/services/api';

const safeAreaTop = ref(0);
const userInfo = ref<any>({});
const formData = reactive({ name: '' });

onMounted(() => {
    const sysInfo = uni.getSystemInfoSync();
    safeAreaTop.value = sysInfo.safeAreaInsets?.top || 20;
    
    const u = getUserInfo();
    userInfo.value = u || {};
    formData.name = u?.name || '';
});

const goBack = () => uni.navigateBack();

const handleSave = async () => {
    if (!formData.name) return uni.showToast({ title: '姓名不能为空', icon: 'none' });
    
    uni.showLoading({ title: '保存中...' });
    try {
        const res = await authApi.updateProfile({ name: formData.name });
        // Update local storage
        setUserInfo(res.user);
        
        userInfo.value = res.user; // Update view
        uni.hideLoading();
        uni.showToast({ title: '保存成功', icon: 'success' });
        setTimeout(() => uni.navigateBack(), 1000);
    } catch (e: any) {
        uni.hideLoading();
        uni.showToast({ title: e.message || '保存失败', icon: 'none' });
    }
};

const toChangeContact = (type: string) => {
    uni.showToast({ title: '功能开发中', icon: 'none' });
};
</script>
