// pc-version/src/pages/Settings.tsx
import React from 'react';
import MobileHeader from '../components/MobileHeader';
import { User, Lock, Bell, ChevronRight } from 'lucide-react';
import { clearAuth } from '../services/api';
import { useNavigate } from 'react-router-dom';

export default function Settings() {
    const navigate = useNavigate();

    const handleLogout = () => {
        if (window.confirm("确定要退出登录吗？")) {
            clearAuth();
            navigate('/login');
        }
    };

    const menuItems = [
        { icon: User, label: '个人信息', path: '/profile' },
        { icon: Lock, label: '修改密码', path: '/change-password' }, // Maybe modal or new page?
        { icon: Bell, label: '消息通知设置', path: '/notifications' },
    ];

    return (
        <div className="min-h-screen bg-gray-50 pt-14">
            <MobileHeader title="个人设置" />

            <div className="mt-2 bg-white">
                {menuItems.map((item, idx) => (
                    <div
                        key={idx}
                        className={`flex items-center justify-between px-4 py-4 active:bg-gray-50 cursor-pointer ${idx !== menuItems.length - 1 ? 'border-b border-gray-100' : ''}`}
                        onClick={() => navigate(item.path)}
                    >
                        <div className="flex items-center gap-3">
                            <item.icon className="w-5 h-5 text-gray-500" strokeWidth={1.5} />
                            <span className="text-sm font-medium text-gray-800">{item.label}</span>
                        </div>
                        <ChevronRight className="w-4 h-4 text-gray-400" />
                    </div>
                ))}
            </div>

            <div className="p-4 mt-8">
                <button
                    onClick={handleLogout}
                    className="w-full bg-white text-gray-600 py-3.5 rounded-xl font-medium shadow-sm hover:bg-gray-50 transition-colors"
                >
                    退出登录
                </button>
            </div>
        </div>
    );
}

// uniapp-version/src/pages/user/settings.vue
<template>
  <view class="min-h-screen bg-gray-50 pb-10">
    <!-- Header -->
    <view class="bg-white px-4 py-3 flex flex-row items-center justify-between sticky top-0 z-10 border-b border-gray-100" :style="{ paddingTop: safeAreaTop + 'px' }">
       <view @click="goBack" class="p-1"><AppIcon name="chevron-left" :size="24" color="#374151" /></view>
       <text class="text-lg font-bold text-gray-800">设置</text>
       <view class="w-6"></view>
    </view>

    <view class="bg-white mt-4">
        <view class="flex flex-row items-center justify-between px-4 py-4 border-b border-gray-100 active:bg-gray-50" @click="goPage('/pages/user/profile-info')">
             <view class="flex flex-row items-center gap-3">
                 <AppIcon name="user" :size="20" color="#4B5563" />
                 <text class="text-gray-800 font-medium">个人信息</text>
             </view>
             <AppIcon name="chevron-right" :size="18" color="#9CA3AF" />
        </view>
        <view class="flex flex-row items-center justify-between px-4 py-4 border-b border-gray-100 active:bg-gray-50" @click="goPage('/pages/user/change-password')">
             <view class="flex flex-row items-center gap-3">
                 <AppIcon name="lock" :size="20" color="#4B5563" />
                 <text class="text-gray-800 font-medium">修改密码</text>
             </view>
             <AppIcon name="chevron-right" :size="18" color="#9CA3AF" />
        </view>
        <view class="flex flex-row items-center justify-between px-4 py-4 border-b border-gray-100 active:bg-gray-50" @click="goPage('/pages/user/notification-settings')">
             <view class="flex flex-row items-center gap-3">
                 <AppIcon name="bell" :size="20" color="#4B5563" />
                 <text class="text-gray-800 font-medium">消息通知设置</text>
             </view>
             <AppIcon name="chevron-right" :size="18" color="#9CA3AF" />
        </view>
    </view>

    <view class="mt-8 px-4">
        <button class="bg-white text-red-500 font-medium py-3 rounded-xl border border-gray-200" @click="handleLogout">
            退出登录
        </button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import AppIcon from '@/components/Icons.vue';
import { logout } from '@/services/api';

const safeAreaTop = ref(0);
onMounted(() => {
    const sysInfo = uni.getSystemInfoSync();
    safeAreaTop.value = sysInfo.safeAreaInsets?.top || 20;
});
const goBack = () => uni.navigateBack();
const goPage = (url: string) => uni.navigateTo({ url });

const handleLogout = () => {
    uni.showModal({
        title: '提示',
        content: '确定要退出登录吗？',
        success: (res: any) => {
            if (res.confirm) {
                logout();
                // Relaunch to index to reset state
                uni.reLaunch({ url: '/pages/index/index' });
            }
        }
    })
};
</script>
