// uniapp-version/src/pages/cart/cart.vue
<template>
  <view class="min-h-screen bg-gray-50 pb-24">
    <!-- Header -->
    <view class="bg-white px-4 py-3 flex flex-row items-center justify-between sticky top-0 z-10 border-b border-gray-100" :style="{ paddingTop: safeAreaTop + 'px' }">
       <view @click="goBack" class="p-1"><AppIcon name="chevron-left" :size="24" color="#374151" /></view>
       <text class="text-lg font-bold text-gray-800">我的购物车</text>
       <view class="w-6"></view>
    </view>

    <!-- Cart Items -->
    <view class="p-4">
        <view v-if="items.length === 0" class="flex flex-col items-center justify-center pt-20">
            <AppIcon name="shopping-cart" :size="48" color="#d1d5db" />
            <text class="text-gray-400 mt-4">购物车是空的</text>
        </view>

        <view v-else class="flex flex-col gap-4">
            <view v-for="item in items" :key="item.id" class="bg-white rounded-xl p-4 flex flex-row gap-3 items-start relative overflow-hidden" :class="{'opacity-60': !item.available}">
                <!-- Checkbox -->
                <view class="mt-8" @click="toggleSelect(item.id)">
                     <view class="w-5 h-5 rounded-full border border-gray-300 flex items-center justify-center" :class="{'bg-emerald-500 border-emerald-500': selectedItems.includes(item.id)}">
                         <AppIcon v-if="selectedItems.includes(item.id)" name="check" :size="14" color="#fff" />
                     </view>
                </view>

                <!-- Image -->
                <image :src="item.image" mode="aspectFill" class="w-20 h-20 rounded-lg bg-gray-100 flex-shrink-0" />

                <!-- Info -->
                <view class="flex-1 flex flex-col justify-between h-20">
                    <view>
                        <text class="text-base font-bold text-gray-800 line-clamp-1">{{ item.title }}</text>
                        <text class="text-xs text-gray-500 mt-1 block">{{ item.specs }}</text>
                        <text v-if="!item.available" class="text-xs text-red-500 mt-1 block">该区域暂时不支持配送</text>
                    </view>
                    <view class="flex flex-row justify-between items-end">
                        <text class="text-emerald-600 font-bold">¥{{ item.price }}</text>
                        
                        <!-- Qty Control -->
                        <view class="flex flex-row items-center bg-gray-100 rounded-lg">
                            <view @click.stop="updateQty(item.id, -1)" class="w-7 h-7 flex items-center justify-center text-gray-600 font-bold">-</view>
                            <text class="text-sm font-medium w-6 text-center">{{ item.quantity }}</text>
                            <view @click.stop="updateQty(item.id, 1)" class="w-7 h-7 flex items-center justify-center text-gray-600 font-bold">+</view>
                        </view>
                    </view>
                </view>
            </view>
        </view>

        <view class="mt-6 p-3 bg-orange-50 rounded-lg border border-orange-100">
            <view class="flex flex-row gap-2">
                <AppIcon name="alert-circle" :size="16" color="#f97316" />
                <view class="flex-1">
                     <text class="text-xs text-orange-700 leading-tight">温馨提示：服务类商品请确认上门地址是否在服务范围内。如有疑问请联系客服。</text>
                </view>
            </view>
        </view>
    </view>

    <!-- Bottom Action Bar -->
    <view class="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 p-4 pb-8 flex flex-row items-center justify-between shadow-lg z-20">
        <view class="flex flex-row items-center gap-2" @click="toggleSelectAll">
             <view class="w-5 h-5 rounded-full border border-gray-300 flex items-center justify-center" :class="{'bg-emerald-500 border-emerald-500': isAllSelected && items.length > 0}">
                 <AppIcon v-if="isAllSelected && items.length > 0" name="check" :size="14" color="#fff" />
             </view>
             <text class="text-gray-600 text-sm">全选</text>
        </view>

        <view class="flex flex-row items-center gap-4">
            <view class="flex flex-col items-end">
                <text class="text-xs text-gray-500">合计 (不含运费)</text>
                <text class="text-lg font-bold text-emerald-600">¥{{ totalPrice }}</text>
            </view>
            <button class="bg-emerald-600 text-white px-6 py-2 rounded-xl font-bold text-sm m-0" @click="handleCheckout">
                去结算({{ selectedItems.length }})
            </button>
        </view>
    </view>

  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import AppIcon from '@/components/Icons.vue';

const safeAreaTop = ref(0);

onMounted(() => {
    const sysInfo = uni.getSystemInfoSync();
    safeAreaTop.value = sysInfo.safeAreaInsets?.top || 20;
});

const goBack = () => uni.navigateBack();

// Mock Data
const items = ref([
    { id: 1, title: '深度保洁服务 - 3小时', specs: '3小时 | 标准清洁剂', price: 199, quantity: 1, image: 'https://images.unsplash.com/photo-1581578731117-104f2a417954?w=200&h=200&fit=crop', available: true },
    { id: 2, title: '空调清洗 - 挂机', specs: '单台 | 高温蒸汽', price: 128, quantity: 2, image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=200&h=200&fit=crop', available: true },
    { id: 3, title: '油烟机清洗', specs: '侧吸式 | 含外观清洁', price: 158, quantity: 1, image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=200&h=200&fit=crop', available: false },
]);

const selectedItems = ref<number[]>([]);

const isAllSelected = computed(() => items.value.length > 0 && selectedItems.value.length === items.value.length);

const totalPrice = computed(() => {
    return items.value
        .filter(item => selectedItems.value.includes(item.id))
        .reduce((sum, item) => sum + item.price * item.quantity, 0);
});

const toggleSelect = (id: number) => {
    if (selectedItems.value.includes(id)) {
        selectedItems.value = selectedItems.value.filter(i => i !== id);
    } else {
        selectedItems.value.push(id);
    }
};

const toggleSelectAll = () => {
    if (isAllSelected.value) {
        selectedItems.value = [];
    } else {
        selectedItems.value = items.value.map(i => i.id);
    }
};

const updateQty = (id: number, delta: number) => {
    const item = items.value.find(i => i.id === id);
    if (!item) return;
    const newQty = item.quantity + delta;
    if (newQty > 0) item.quantity = newQty;
};

const handleCheckout = () => {
    if (selectedItems.value.length === 0) return uni.showToast({title: '请选择商品', icon: 'none'});
    uni.showToast({title: '正在前往结算...', icon: 'none'});
};
</script>

<style scoped>
/* Tailwind utilities are usually available via Windi/Uni-Tailwind, but defining basic fallback */
.line-clamp-1 {
    overflow: hidden;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 1;
}
</style>

// pc-version/src/pages/Cart.tsx
import React, { useState } from 'react';
import MobileHeader from '../components/MobileHeader';
import { Minus, Plus, AlertCircle, Image as ImageIcon, Circle, CheckCircle2 } from 'lucide-react';

interface CartItem {
    id: number;
    title: string;
    time?: string;
    price: number;
    count: number;
    image?: string;
    unavailable?: boolean;
}

export default function Cart() {
    const [items, setItems] = useState<CartItem[]>([
        { id: 1, title: '清洁打扫小时清洁打扫打扫清洁小时', time: '2025/06/24 18:00', price: 185.00, count: 1, image: 'https://images.unsplash.com/photo-1581578731117-1045293d2f24?w=200&h=200&fit=crop' },
        { id: 2, title: '清洁打扫3小时清洁打扫', time: '2025/06/24 18:00', price: 185.00, count: 1, image: 'https://images.unsplash.com/photo-1527515673510-813d3143c151?w=200&h=200&fit=crop' },
        { id: 3, title: '清洁打扫3小时清洁打扫打扫', price: 0, count: 1, unavailable: true },
        { id: 4, title: '清洁打扫3小时清洁打扫打扫', time: '2025/06/24 18:00', price: 185.00, count: 1, image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=200&h=200&fit=crop' },
    ]);

    const [selectedIds, setSelectedIds] = useState<number[]>([2]);

    const toggleSelect = (id: number) => {
        if (selectedIds.includes(id)) {
            setSelectedIds(selectedIds.filter(i => i !== id));
        } else {
            setSelectedIds([...selectedIds, id]);
        }
    };

    const toggleSelectAll = () => {
        const availableIds = items.filter(i => !i.unavailable).map(i => i.id);
        if (selectedIds.length === availableIds.length) {
            setSelectedIds([]);
        } else {
            setSelectedIds(availableIds);
        }
    };

    const updateCount = (id: number, delta: number) => {
        setItems(items.map(item => {
            if (item.id === id) {
                const newCount = Math.max(1, item.count + delta);
                return { ...item, count: newCount };
            }
            return item;
        }));
    };

    const totalPrice = items
        .filter(item => selectedIds.includes(item.id))
        .reduce((sum, item) => sum + item.price * item.count, 0);

    const isAllSelected = items.filter(i => !i.unavailable).length > 0 &&
        items.filter(i => !i.unavailable).every(i => selectedIds.includes(i.id));

    return (
        <div className="min-h-screen bg-gray-50 pb-32 pt-14">
            <MobileHeader title="购物车" />

            <div className="p-4 space-y-4">
                {items.map(item => (
                    <div key={item.id} className="bg-white rounded-xl p-4 flex gap-3 shadow-sm border border-gray-100">
                        {/* Checkbox */}
                        <div className="flex items-center">
                            <button
                                onClick={() => !item.unavailable && toggleSelect(item.id)}
                                disabled={item.unavailable}
                                className={`rounded-full transition-colors ${item.unavailable ? 'text-gray-200 cursor-not-allowed' : selectedIds.includes(item.id) ? 'text-primary-500' : 'text-gray-300'}`}
                            >
                                {selectedIds.includes(item.id) ? <CheckCircle2 className="w-6 h-6 fill-current" /> : <Circle className="w-6 h-6" />}
                            </button>
                        </div>

                        {/* Image */}
                        <div className="w-24 h-24 bg-gray-100 rounded-lg flex-shrink-0 relative overflow-hidden">
                            {item.image ? (
                                <img src={item.image} alt="" className="w-full h-full object-cover" />
                            ) : (
                                <div className="w-full h-full flex items-center justify-center text-gray-300">
                                    <ImageIcon className="w-8 h-8" />
                                </div>
                            )}
                            {item.unavailable && (
                                <div className="absolute inset-0 bg-white/60 flex items-end justify-center pb-1">
                                    {/* Optional overlay */}
                                </div>
                            )}
                            {item.id === 1 && <span className="absolute bottom-1 right-1 text-primary-500"><AlertCircle className="w-4 h-4" /></span>}
                            {/* Trying to mimic screenshot icon overlay if any. Item 1 has warning icon in screenshot? No, Item 1 has check, Item 3 unavailable. 
                                Actually Item 3 has a picture placeholder icon at bottom right. */}
                            {item.unavailable && (<span className="absolute bottom-1 right-1 text-blue-400"><ImageIcon className="w-4 h-4" /></span>)}
                            {/* Item 1 has a blue i-circle info icon? */}
                            {item.id === 1 && <span className="absolute bottom-1 right-1 text-cyan-500"><AlertCircle className="w-4 h-4" /></span>}
                        </div>

                        {/* Content */}
                        <div className="flex-1 flex flex-col justify-between">
                            <div>
                                <h3 className={`text-sm font-medium line-clamp-2 ${item.unavailable ? 'text-gray-400' : 'text-gray-800'}`}>
                                    {item.title}
                                </h3>
                                {item.unavailable ? (
                                    <p className="text-xs text-gray-400 mt-1">服务不可用</p>
                                ) : (
                                    <p className="text-xs text-gray-500 mt-1">预约时间: {item.time}</p>
                                )}
                            </div>

                            {!item.unavailable && (
                                <div className="flex items-center justify-between mt-2">
                                    <span className="text-orange-500 font-bold">${item.price.toFixed(2)}</span>
                                    <div className="flex items-center gap-1">
                                        <button
                                            onClick={() => updateCount(item.id, -1)}
                                            className="w-7 h-7 flex items-center justify-center bg-cyan-500 text-white rounded text-lg font-medium active:bg-cyan-600"
                                        >-</button>
                                        <span className="w-8 text-center text-sm font-medium">{item.count}</span>
                                        <button
                                            onClick={() => updateCount(item.id, 1)}
                                            className="w-7 h-7 flex items-center justify-center bg-cyan-500 text-white rounded text-lg font-medium active:bg-cyan-600"
                                        >+</button>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Bottom Warning */}
            <div className="fixed bottom-16 left-0 right-0 bg-orange-100 text-orange-500 text-xs px-4 py-2">
                多个订单合并支付时，将生成多个订单
            </div>

            {/* Sticky Footer */}
            <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 h-16 flex items-center justify-between px-4 z-40">
                <div className="flex items-center gap-2" onClick={toggleSelectAll}>
                    <button className={`${isAllSelected ? 'text-primary-500' : 'text-gray-300'}`}>
                        {isAllSelected ? <CheckCircle2 className="w-6 h-6 fill-current" /> : <Circle className="w-6 h-6" />}
                    </button>
                    <span className="text-sm text-gray-600">全选</span>
                </div>

                <div className="flex items-center gap-4">
                    <span className="text-sm text-gray-600">合计: <span className="text-gray-900 font-bold">${totalPrice.toFixed(2)}</span></span>
                    <button className="bg-cyan-500 text-white px-8 py-2.5 rounded-full font-medium shadow-lg shadow-cyan-500/30">
                        结算({selectedIds.length})
                    </button>
                </div>
            </div>
        </div>
    );
}
